const simpleGit = require("simple-git");
const { Octokit } = require("@octokit/rest");
const path = require("path");

const git = simpleGit();

/**
 * Clone repository
 */
async function cloneRepository(repoUrl, clonePath) {

  console.log("📥 Cloning repository...");

  await git.clone(repoUrl, clonePath);

  return clonePath;
}

/**
 * Create fix branch
 */
async function createFixBranch(repoPath) {

  const repoGit = simpleGit(repoPath);

  const branchName = "codeguardian-fix";

  await repoGit.checkoutLocalBranch(branchName);

  return branchName;
}

/**
 * Commit changes
 */
async function commitChanges(repoPath) {

  const repoGit = simpleGit(repoPath);

  await repoGit.add(".");

  await repoGit.commit("fix: security vulnerabilities detected by CodeGuardian");

}

/**
 * Push branch to GitHub
 */
async function pushChanges(repoPath, branchName, repoUrl, token) {

  const repoGit = simpleGit(repoPath);

  const authenticatedUrl = repoUrl.replace(
    "https://",
    `https://${token}@`
  );

  await repoGit.push(authenticatedUrl, branchName);

}

/**
 * Create Pull Request
 */
async function createPullRequest(repoUrl, branchName, token) {

  const parts = repoUrl.split("/");

  const owner = parts[3];

  const repo = parts[4].replace(".git","");

  const octokit = new Octokit({
    auth: token
  });

  const pr = await octokit.pulls.create({

    owner: owner,

    repo: repo,

    title: "CodeGuardian Security Fix",

    head: branchName,

    base: "main",

    body: "Automated security fixes generated by CodeGuardian."

  });

  return pr.data.html_url;

}

module.exports = {
  cloneRepository,
  createFixBranch,
  commitChanges,
  pushChanges,
  createPullRequest
};